### ISSUE TITLE
Generalize normed_group to seminormed_group

### ISSUE THREAD

**Issue by riccardobrasca** [leanprover-community/lean-liquid#20]
We need seminormed groups (meaning we don't require `∥x∥ = 0 → x = 0`). This means we need pseudometric space (meaning we don't require `d(x,y) = 0 → x = y`, this seems to be the standard terminology, note that this "pseudo" is unrelated to the "pseudo" of `pseudo_normed_group`).

It makes sense to do this directly in mathlib, but at some point we will need to refactor `normed_group_quotient` to allow quotient by a nonclosed subspace.

**Comment by riccardobrasca** [comment]
To start with, I created [6694](https://github.com/leanprover-community/mathlib/pull/6694).

**Comment by riccardobrasca** [comment]
We now have `pseudo_emetric_space` in mathlib! [6716](https://github.com/leanprover-community/mathlib/pull/6716) for `pseudo_metric`.

**Comment by jcommelin** [comment]
Great job! I see that the second PR is also already merged :tada:

**Comment by riccardobrasca** [comment]
And we have [6746](https://github.com/leanprover-community/mathlib/pull/6746) for `semi_normed_group`!

Next episode: `semi_normed_group_hom`.

**Comment by riccardobrasca** [comment]
I made [6762](https://github.com/leanprover-community/mathlib/pull/6762) about `semi_normed_ring`, `semi_normed_space` and so on. This is probably not needed for the LTE, but who knows.

**Comment by riccardobrasca** [comment]
[#6819](https://github.com/leanprover-community/mathlib/pull/6819) for `semi_normed_group_hom`. One this one gets merged we can refactoring `for_mathlib/normed_group_quotient` to allow quotient by a non closed subspace.
